"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _explore_listings from './explore-listings.bones.json'

configureBoneyard({"animate":"pulse"})

registerBones({
  "explore-listings": _explore_listings,
})
